Repository OtagoPolytechnic/CourseMatcher, pull requests merged in 2025-09, with the labels that each got.

#39 Multi query search
  backend/app/__pycache__/main.cpython-313.pyc
  frontend/src/components/SearchBar.tsx
  frontend/src/pages/BachelorIT.tsx
  package-lock.json
Labels: enhancement

#46 UI/UX Improvements: Home Page
  frontend/public/homeIcon.png
  frontend/public/landingIcon.png
  frontend/src/App.tsx
  frontend/src/components/SearchBar.tsx
  frontend/src/pages/BachelorIT.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/ProgramNav.tsx
Labels: pull request

#52 Search Bar Input Issue
  frontend/src/components/SearchBar.tsx
Labels: bug
